config/routes.rb
Rails.application.routes.draw do

  
  #Διαδρομές για εγγραφή, σύνδεση και αποσύνδεση του χρήστη
  root to: 'user#signup'
  get '/signup', to: 'user#signup'
  post '/signup', to: 'user#create'
  get '/login', to: 'user#login'
  post '/login', to: 'user#find'
  get '/logout', to: 'user#logout', as: :logout
  get '/users/:user_id/todo_lists', to: 'todo_lists#index', as: :user_todo_lists

  resources :todo_lists do
    resources :todo_items
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    belongs_to :user
    has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_many :todo_lists
    
    has_secure_password 

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :email, presence: true,
    
                   uniqueness: { case_sensitive: false },
    
                   length: { maximum: 100 },
    
                   format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private
  
    def current_user
      # Implement your logic to fetch the current user using session, token, etc.
      # For example:
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find_by(id: session[user_id])
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index 
        
    end 
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: %i[ show edit update destroy ]

  # GET /todo_items or /todo_items.json
  def index
    @todo_list = TodoList.find(params[:todo_list_id])
    # Assuming TodoList has a has_many association with TodoItem
    @todo_items = @todo_list.todo_items
    end
  

  # GET /todo_items/1 or /todo_items/1.json
  def show
    @todo_item = TodoItem.find(params[:id])
    @todo_list = TodoList.find(params[:todo_list_id])
    #@todo_item = @todo_list.todo_items.find(params[:id])
  end
  

  # GET /todo_items/new
  def new
    @todo_list = TodoList.find(params[:todo_list_id]) # or however you are fetching the todo_list
    @todo_item = @todo_list.todo_items.build
  end
  

  # GET /todo_items/1/edit
  def edit
    @todo_list = TodoList.find(params[:todo_list_id]) # or however you fetch the todo_list
    @todo_item = TodoItem.find(params[:id])
  end

  # POST /todo_items or /todo_items.json
  def create
    @todo_list = TodoList.find(params[:todo_list_id]) # Retrieve the associated todo_list
    @todo_item = @todo_list.todo_items.build(todo_item_params) # Create a new todo_item for that todo_list
  
    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_list_todo_item_path(@todo_list, @todo_item), notice: "Todo item was successfully created." }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /todo_items/1 or /todo_items/1.json
  def update
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = TodoItem.find(params[:id])
  
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to todo_list_todo_item_path(@todo_list, @todo_item), notice: "Todo item was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_todo_items_url(@todo_item.todo_list), notice: "Todo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :completed, :completed_at, :todo_list_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
# TodoListsController
def index
  @user = current_user
  #@todo_list = current_user.todo_lists.build(todo_list_params)
  @todo_lists = current_user.todo_lists
end


  # GET /todo_lists/1 or /todo_lists/1.json
# TodoListsController
def show
  @@todo_list = TodoList.find_by(user_id: params[:user_id])
  @todo_items = @todo_list.todo_items
end


  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
# POST /todo_lists or /todo_lists.json
def create
  @todo_list = current_user.todo_lists.build(todo_list_params)

  respond_to do |format|
    if @todo_list.save
      format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created." }
      format.json { render :show, status: :created, location: @todo_list }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @todo_list.errors, status: :unprocessable_entity }
    end
  end
end


  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list = TodoList.find(params[:id])

    # Destroy associated todo items first (if needed)
    @todo_list.todo_items.destroy_all if @todo_list.todo_items.any?
  
    # Then delete the todo list itself
    @todo_list.destroy!
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def signup
        @user = User.new 
    end

    def login
       
    end

    #Σύνδεση χρήστη
    def find
        @user = User.find_by(email: params[:email])
      
        if @user.present? && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to user_todo_lists_path(user_id: @user.id), notice: 'Logged in successfully'
        else 
          redirect_to login_path, notice: 'Invalid email or password! Please try again.'
        end
      end
      

    #Εγγραφή χρήστη 
        def create
        @user = User.new(user_params)
 
        if @user.save
            session[:user_id]= @user.id
            redirect_to user_todo_lists_path(user_id: @user.id), notice: 'Successfully created account'
 
        else
        
            redirect_to signup_path, notice: 'This email is being used. Please try an other one.'
        end
 
    end

     def logout
        session[:user_id]= nil
        redirect_to signup_path, notice: 'Logged out!'
    end
    private
 
    def user_params
     params.require(:user).permit(:email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
 <title>TodoApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/2ec2a30cc1.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD' crossorigin='anonymous'>

<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js' integrity='sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN' crossorigin='anonymous'></script>
    
  <body class='bg-light'>
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <div class="card mt-5">
    <%= yield %>
    </div>
    </div>
    </div>
    </div>
    </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with(model: [@todo_list, todo_item]) do |form| %>
<% if todo_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.label :completed_at, style: "display: block" %>
    <%= form.datetime_field :completed_at %>
  </div>

<!-- <div>
    <%= form.label :todo_list_id, style: "display: block" %>
    <%= form.text_field :todo_list_id %>
  </div>-->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div id="<%= dom_id todo_item %>">
  <p>
    <strong>Description:</strong>
    <%= todo_item.description %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= todo_item.completed %>
  </p>

  <p>
    <strong>Completed at:</strong>
    <%= todo_item.completed_at %>
  </p>

  <p>
    <strong>Todo list:</strong>
    <%= todo_item.todo_list_id %>
  </p>

</div>

app/views/todo_items/edit.html.erb
<h1>Update todo item</h1>

<%= render "form", todo_item: @todo_item %>

<br>

<div>
<%= link_to "Show this todo item", todo_list_todo_item_path(@todo_list, @todo_item) %>
<br>
<%= link_to "Back to todo items", todo_list_todo_items_path(@todo_list) %>
</div>

app/views/todo_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todo items</h1>

<div id="todo_items">
  <% if @todo_list.todo_items.present? %>
    <ul>
      <% @todo_list.todo_items.each do |todo_item| %>
        <li><%= todo_item.description %></li>
        <%= link_to "Show item", todo_list_todo_item_path(@todo_list, todo_item) %>
      <% end %>
    </ul>
  <% else %>
    <p>No todo items found.</p>
  <% end %>
</div>

<%= link_to "New todo item", new_todo_list_todo_item_path(@todo_list) %>

app/views/todo_items/new.html.erb
<h1>New todo item</h1>

<%= render "form", todo_item: @todo_item %>

<br>
<div>
  <%= link_to "Back to todo items", todo_list_todo_items_path(@todo_list) %>
</div>

app/views/todo_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_item %>

<div>
 &nbsp &nbsp <%= link_to "Update item", edit_todo_list_todo_item_path(@todo_list, @todo_item) %> 
  <br>
 &nbsp &nbsp <%= link_to "Back to todo items", todo_list_todo_items_path(@todo_list) %>
<br>
<br>
  <%= button_to "Delete item", todo_list_todo_item_path(@todo_list, @todo_item),class:'btn btn-primary btn-sm', method: :delete, data: { confirm: "Are you sure?" } %>
  <br>
  <br>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <p>
    <strong>Title:</strong>
    <%= todo_list.title %>
  </p>

</div>

app/views/todo_lists/edit.html.erb
<h1>Editing todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Show this todo list", @todo_list %> |
  <%= link_to "Back to todo lists", todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<div class="card-header d-flex justify-content-between">
  <span>
    Todo Lists

  </span>
    <%= link_to "New todo list", new_todo_list_path, class: 'btn btn-primary btn-sm' %>    
    <% if @user %>
      Logged in as: <%= @user.email %>
      <%= link_to "Logout", logout_path, method: :delete, class: 'btn btn-primary btn-sm' %>
    <% end %>
</div>

<p style="color: green"><%= notice %></p>

<ul class='list-group'>
  <div id="todo_lists">
    <% @todo_lists.each do |todo_list| %>
      <li class="list-group-item">
        <%= render todo_list %>
        <%= link_to "Show todo", todo_list, class: 'btn btn-primary btn-sm' %>
        <ul>
          <% todo_list.todo_items.each do |todo_item| %>
            <li><%= todo_item.description %></li>
            <%= link_to "Show item", todo_list_todo_item_path(todo_list, todo_item) %>
          <% end %>
        </ul>
        <%= link_to "Show all items", todo_list_todo_items_path(todo_list), class: 'btn btn-primary btn-sm' %>
      </li>
    <% end %>
  </div>
</ul>

app/views/todo_lists/new.html.erb
<h1>New todo list</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div>
  <%= link_to "Back to todo lists", todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p style="color: green"><%= notice %></p>

&nbsp <%= render @todo_list %>

<div>
 &nbsp  <%= link_to "Update todo list", edit_todo_list_path(@todo_list) %> 
  <br>
 &nbsp  <%= link_to "Back to todo lists", todo_lists_path %> 
 <br>
 <br>
 <br>
<%= button_to "Delete todo list", @todo_list,  class:'btn btn-primary btn-sm',method: :delete %>
  <br>
  <br>
</div>

app/views/user/login.html.erb
<div class='container'>

 <div class=”row justify-content-center”>

   <div class='col-5'>

     <div class='mt-3'>

       <h1> Sign In </h1>

     </div>
<p style="color: red"><%= notice %></p>

     <%= form_with model: @user, url: '/login#find' do |form| %>

        <div class='form-group row mt-3'>

          <%= form.label :email, 'Email' %>

          <%= form.text_field :email, class: 'form-control',

                   placeholder: 'Enter your email address' %>

        </div>

        <div class='form-group row mt-3'>

          <%= form.label :password, 'Password' %>

          <%= form.password_field :password, class: 'form-control',

                                placeholder: 'Enter your password' %>

        </div>

        <div class=' form-group row mt-3'>

         <%= form.submit 'Sign In', class: 'btn btn-primary' %>

        </div>

     <% end %>

   </div>

 </div>

</div>

app/views/user/signup.html.erb
<div class='container'>

 <div class=”row justify-content-center”>

   <div class='col-5'>

     <div class='mt-3'>

       <h1> Sign Up </h1>

     </div>
<p style="color: red"><%= notice %></p>

     <%= form_with model: @user, url: '/signup#create' do |form| %>
        <div class='form-group row mt-3'>

          <%= form.label :email, 'Email' %>

          <%= form.text_field :email, class: 'form-control',

                   placeholder: 'Enter your email address' %>

        </div>

        <div class='form-group row mt-3'>

          <%= form.label :password, 'Password' %>

          <%= form.password_field :password, class: 'form-control',

                                placeholder: 'Enter your password' %>

        </div>

        <div class='form-group row mt-3'>

          <%= form.label :password_confirmation, 'Confirm password' %>

          <%= form.password_field :password_confirmation, class: 'form-control',   placeholder: 'Please enter the password again' %>

        </div>

        <div class=' form-group row mt-3'>

         <%= form.submit 'Sign Up', class: 'btn btn-primary' %>

        </div>

     <% end %>

   </div>

 </div>

</div>